[book]
authors = ["zzy"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Word List"

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
git-repository-url = "https://mineil.github.io/Englishlr/"
git-repository-icon = "fa-github"

[output.html.print]
enable = true

[output.html.search]
enable = true
